ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      \curl -sSL https://get.rvm.io | bash -s stable --rails &&
      bundle install --without production &&
      yarn install
    command: >
      rails server