source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'

# gem 'bcrypt', '~> 3.1.7'
# gem 'capistrano-rails', group: :development
# gem 'duktape'
# gem 'mini_magick', '~> 4.8'
# gem 'redis', '~> 4.0'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'puma', '~> 3.12'
gem 'rails', '~> 5.2.4', '>= 5.2.4.1'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

# Custom gems for this project
gem 'awesome_print'
gem 'better_errors'
gem 'breadcrumbs_on_rails'
gem 'cocoon'
gem 'custom_error_message', '~> 1.1', '>= 1.1.1'
gem 'data-confirm-modal'
gem 'dependent-fields-rails'
gem 'devise'
gem 'inline_svg'
gem 'gravatar_image_tag'
gem 'non-stupid-digest-assets', '~> 1.0', '>= 1.0.8'
gem 'rails_db', '~> 2.3.0'
gem 'rails-i18n', '~> 5.1'
gem 'ransack'
gem 'roadie-rails', '~> 2.1'
gem 'selectize-rails'
gem 'simple_form'
gem 'translate_enum'
gem 'tty-spinner'
gem 'via_cep'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara'
  gem 'database_cleaner', '~> 1.7'
  gem 'factory_bot_rails', '~> 4.0'
  gem 'faker'
  gem 'httparty'
  gem 'rails-controller-testing'
  gem 'rspec-json_expectations'
  gem 'rspec-rails', '~> 3.6'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webdrivers'
  gem 'webmock'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'spring-commands-rspec'
  gem 'rails-erd'
  gem 'bullet'
  gem 'guard', '~> 2.15'
  gem 'guard-livereload', require: false
  gem 'rack-livereload'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
